# Generated by Django 5.1.7 on 2025-05-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteTool',
            fields=[
                ('ip_address', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('os_name', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=50)),
                ('sample1', models.CharField(blank=True, max_length=100, null=True)),
                ('sample2', models.CharField(blank=True, max_length=100, null=True)),
                ('sample3', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('green', 'Green'), ('red', 'Red'), ('grey', 'Grey')], max_length=10, null=True)),
            ],
            options={
                'db_table': 'remote_tool',
                'managed': False,
            },
        ),
    ]
